---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: businessbot

resources:
  - ../../base

namePrefix: whatsapp-gateway-

labels:
  - pairs:
      app: whatsapp-gateway
      component: gateway
      version: v1
    includeSelectors: true

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: ghcr.io/gabrielwyp/business-bot-microservice
    newName: ghcr.io/gabrielwyp/businessbot-whatsapp-gateway
    newTag: latest
