apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reto-movistar

resources:
  - 00-storage/storage.yaml
  - 01-rbac/serviceaccount.yaml
  - 02-config/configmap.yaml
  - 03-workloads/back-deployment.yaml
  - 03-workloads/front-deployment.yaml
  - 04-networking/back-service.yaml
  - 04-networking/front-service.yaml
  - 04-networking/analyst-auth-middleware.yaml
  - 04-networking/ingressroute.yaml
  - 05-operations/backup-cronjob.yaml

images:
  - name: ghcr.io/gabrielwyp/reto-movistar-back
    newName: ghcr.io/gabrielwyp/reto-movistar-back
    newTag: bootstrap
  - name: ghcr.io/gabrielwyp/reto-movistar-front
    newName: ghcr.io/gabrielwyp/reto-movistar-front
    newTag: bootstrap
