apiVersion: v1
kind: ConfigMap
metadata:
  name: reto-movistar-config
  labels:
    app.kubernetes.io/name: reto-movistar
data:
  SONIA_ENVIRONMENT: production
  SONIA_FRONTEND_DIR: /app/no-frontend
  SONIA_LOG_LEVEL: INFO
  SONIA_PORT: "8080"
  SONIA_BI_MODEL: deepseek-v4-flash
