apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-PV/pv.yaml
  - 01-PV/storageclass.yaml
  - 02-config/namespace.yaml
  - 03-serviceMonitor/serviceMonitor.yaml
  - 04-loki/pv.yaml
  - 04-loki/pvc.yaml
  - 04-loki/configmap.yaml
  - 04-loki/deployment.yaml
  - 04-loki/service.yaml
  - 04-loki/grafana-datasource.yaml
  - 05-promtail/rbac.yaml
  - 05-promtail/configmap.yaml
  - 05-promtail/daemonset.yaml
