---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-analysis-config
  labels:
    app: sentiment-analysis
data:
  SENTIMENT_SERVICE_URL: "http://sentiment-model-service:8001"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  APP_MODE: "PRODUCTION"
  REPOSITORY: "ghcr.io"
---
