---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-base
spec:
  template:
    spec:
      containers:
      - name: app
        ports:
        - name: http
          containerPort: 8001
        env:
        - name: SERVICE_NAME
          value: "chatbot"
        - name: PORT
          value: "8001"
        startupProbe:
          httpGet:
            path: /health
            port: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        envFrom:
        - configMapRef:
            name: business-bot-config
        - secretRef:
            name: business-bot-global-secrets
        - secretRef:
            name: chatbot-secrets
