apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: business-bot-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`business-bot.ikigais.app`)
    kind: Rule
    services:
    - name: whatsapp-gateway-service
      port: 3000