---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-web-service
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-model-service
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP

---
