apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: business-bot-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: business-bot-sa
  namespace: default
roleRef:
  kind: Role
  name: business-bot-role
  apiGroup: rbac.authorization.k8s.io