apiVersion: v1
kind: Service
metadata:
  name: asistente-proveedor-web
  labels:
    app.kubernetes.io/name: asistente-proveedor
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: asistente-proveedor
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
